### ISSUE TITLE
seperate thread for pythonqt [sf#58]

### ISSUE THREAD

**Issue by mantaraya36** [CsoundQt/CsoundQt#187]
**Reported by joachimheintz on 2013-03-19 22:50 UTC**
avoid hanging csoundqt by a code like:
from time import sleep
for i in range(5):
print i
sleep(1)

as we discussed by mail, make pythonqt run in a seperate thread might be the best solution

**Comment by bhagerty** [comment]
Is PythonQt—or support for it—dead? I notice that the build instructions for CsoundQt directs users who plan to use PythonQt to use Qt 5.5.1 on Linux—a version that is from 2015, I think. Is that still accurate? It looks like PythonQt is mostly being developed here now: https://github.com/MeVisLab/pythonqt

**Comment by bhagerty** [comment]
So I think that the build instructions for CsoundQt are almost certainly wrong when they warn users of PythonQt to use Qt 5.5.1 on Linux. The current version of PythonQt is being actively developed at [MeVisLab/pythonqt](https://github.com/MeVisLab/pythonqt/issues/17), and a dev over there said, [in response to an issue I raised,](https://github.com/MeVisLab/pythonqt/issues/17) that they use PythonQt with Qt 5.15 for a project called Slicer.

**Comment by tarmoj** [comment]
Hi,

Thanks for the note!

No, PythonQt is constantly supported, the build instructions are outdated... Please specify where did you read it - BUILD.md? Wiki Pages?
On Linux you have to build PythonQt yourself, On MacOS it included in the bundle (in fact there are two pacakges -  on with and one without pythonqt), on Windows it is currently left out since many people do not have python installed and it caused crashes that were distracting for new users.

Until now PythonQt 3.2 and quite recent code from their Git https://github.com/MeVisLab/pythonqt are tested.
There is also work by Joachim Heintz on using python3 to build and use PythonQt within CsoundQt (not included yet in the main repo): https://github.com/CsoundQt/CsoundQt/tree/python3

Best!

tarmo
