### ISSUE TITLE
Templates always open Save File dialog

### ISSUE THREAD

**Issue by joachimheintz** [CsoundQt/CsoundQt#208]
when selecting a file from File > Templates, it is not only opened, but also immediately a "Save File as ..." dialog is shown.
i had a look in qutecsound.cpp but cannot see the reason.

**Comment by tarmoj** [comment]
The function is CsoundQt::openTemplate() qutecsound.cpp::430

I think the idea of "Save as" is actually good -  otherwise  user can easily overwrite the template if he makes changes and presses Run.
You can always press "OK" in "Save as" dialog if you decide so (ie not to change the name).
Another option could be to display a warning "Don't forget to save the file with different file if you do any changes" but I think it is less safe.

And a hint for finding way in the code: in QtCreator search bar enter ":<sapce>" for looking for functions and classes and the try to type what intrests you. For example:
: templa
gives already quite good suggestions.

If you think things are fine this way, please close the issue or we can definitely solve it in some way more clear for users.

tarmo

**Comment by joachimheintz** [comment]
thanks for the explanation and also for the tip how to find things like this!

ok — now i understand that is no bug but meant to work in this way.  i expected it to work in the same way as the "open recent" menu.  but if you think it is good this way, i can live with it.  and perhaps it is a usual behaviour which i simply do not know.  so i will close this issue.

**Comment by fsateler** [comment]
> Another option could be to display a warning "Don't forget to save the file with different file if you do any changes" but I think it is less safe.

I think the real fix is to have csoundqt save to a temporary file instead of the real file when running a file.
