### ISSUE TITLE
Can't build standalone program?

### ISSUE THREAD

**Issue by Martonius** [CsoundQt/CsoundQt#217]
Getting an error when trying to open built program. "The procedure entry point _Z21qRegisterResourceDataiPKhSO_SO_ could not be located in the dynamic link library Qt5Core.dll."
I am new to building programs myself, so i'm not sure if I may be doing something wrong.

**Comment by tarmoj** [comment]
Hi,

Thanks for building on Windows - not many people do that but it is good
idea.

Please give some more inforation -
I guess you are on Windows? Which version?  And you built CsoundQt
yourself?  With QtCreator? Which compiler and which archidecture (32/64
bit, is it mingw or MS Visual studio compiler)? Does it work when you run
it in QtCreator? Which version of Csound do you have installed?

The error tells that th Qt libraries are not found or there is conflict
with the Qt libraries of Csound installation.
Deploying (copying everything needed to the folder of your binary) on
Windows is a bit tricky, if it works from QtCreator, it is already good.
​
I am travelling and cannot answer soon. I think it is good to continue in
the qutecsound mailing lista as it is not exactly a bug report..
https://lists.sourceforge.net/lists/listinfo/qutecsound-users

Best!
tarmo

**Comment by hlolli** [comment]
What command did you execute that caused this error? Looks like you have
Qt5 installed but the error is strange, as if something is broken deeper,
do you have 32bit build set on, or did you build Qt5 with 32bits?

2016-10-26 14:48 GMT+02:00 Marty Carlton <notifications@github.com>:

**Comment by Martonius** [comment]
I built CsoundQt with 
(Qt Creator 4.1.0
Based on Qt 5.7.0 (MSVC 2013, 32 bit)
Built on Aug 24 2016 14:56:50
From revision 8c80a86266)
on a Windows 7 machine. I did not build QtCreator myself.
This error happened when I tried to open the CsoundQt-d-cs6.exe after I built it. It works to run it through QtCreator, but even swapping that .exe for the current one I have in my Program Files folder gives me the same error.

**Comment by tarmoj** [comment]
Hi,

Ok, very good that your build works otherwise.
Your problem is that when you run from QtCreator the correct path to the Qt
libraries used in the build is set. Otherwise the system looks for the
first place it finds them amoung the directories in the PATH environment
variable that is probable Program Files/Csound6_x64 or whereever Csound is
installed. I think CsoundQt of the official installer is built using Qt
5.6.0 and since your build requires 5.7, there is the conflict.

I am not on Windows myself but there is a post that could help:
https://forum.qt.io/topic/41958/solved-program-exe-runs-in-qt-creator-but-can-t-find-dlls-when-run-outside-of-qt-creator/4
- create a .bat file with setting PATH to your Qt libs and try then.
Hava a look also to http://doc.qt.io/qt-5/windows-deployment.html

Please let us know how it goes!

tarmo

2016-10-27 9:46 GMT-03:00 Marty Carlton <notifications@github.com>:

**Comment by Martonius** [comment]
Just used the .bat file technique, as the command line work looked a little daunting to this newb. It works!!! Thanks for the help!

**Comment by tarmoj** [comment]
I am glad it worked! It was also something to learn for me -  perhaps I can
add some lines to create such batch file with "make install" command in
QtCreator.
If there is something you would like to add to the build instruction,
please feel free to edit the wiki

https://github.com/CsoundQt/CsoundQt/wiki/Building-on-Windows-with-QtCreator

(There are many things changed, I need to updated the wiki pages anyway
before next release).

Tarmo

2016-10-28 9:38 GMT-03:00 Marty Carlton <notifications@github.com>:
