### ISSUE TITLE
WebEngine Build Runs ".html" But Not ".csd" with "<html>"

### ISSUE THREAD

**Issue by gogins** [CsoundQt/CsoundQt#227]
The cause is that the HTML wrapper readScore function always enqueues events to the HTML wrapper thread routine, but in the .csd runs that routine is not used; the CsoundEngine performance thread object's thread routine is used instead.

Probably the solution would be to refactor a lot of the performance thread code. There should be an abstract base class containing all functionality that is required for both .csd and .html performances. Then there should be   one subclass for .csd performance and one subclass for .html performance. The correct class should be injected into to the actual JavaScript context, where the JavaScript signatures will be identical for both classes.

In the meantime, running a .html file in CsoundQt works fine, and running non-HTML .csd pieces works fine.

**Comment by gogins** [comment]
This may not go into Csound 6.09. I need to merge the qthtml branch back into develop first.

**Comment by tarmoj** [comment]
If you don't mind, let's not merge qhtml into develop yet - before when it
is fully functional and tested, I suggest to keep it separated still and
aim for 0.9.5 to release the html support for all platforms.
Tarmo

19.05.2017 17:41 kirjutas kuupäeval "Michael Gogins" <
notifications@github.com>:

**Comment by gogins** [comment]
It would not be built by default. But the longer we put off merging it the
harder it will be to merge. Also, I was not planning to do this until
Csound 6.09 is released.

Best,
Mike

**Comment by gogins** [comment]
On second thought, rather than merge the HTML branch into the develop
branch, I will merge the develop branch into the HTML branch and so bring
it up to date. I will then continue working in that branch.

Best,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by tarmoj** [comment]
Sounds logical.

I have carried in my mind (for moths) also working on that, especially 
integrating CsoundEngine class and its performance thread into perfomring html 
files. Let's be in touch about what we do to optimize the effort!

tarmo

**Comment by gogins** [comment]
Currently both <html> in csd and standalone HTML work up to the point where, in standalone HTML,   csoundPerformKsmps ends prematurely with -2. That is because the csoundStart function was already called in the CsoundEngine but there was no score. If we can find a workaround for this refactoring a lot of code may not be necessary.

I mean a workaround in CsoundQt code not a workaround in HTML code, I already have a workaround in HTML code but I don't want people to have to fiddle with that.

I have an idea for setting a flag in the CsoundHtmlWrapper object if the file is .html, then the other functions can use that flag to work around the differences. Probably all that really needs to be done is not to start the performance at all if that flag has been set.

**Comment by gogins** [comment]
I have traced through CsoundQt and now understand at least some of why the html-only performance is not working.

When CsoundQt runs a piece whether a regular CSD file or a CSD file containing an embedded HTML element, the sequence of Csound API calls is:

1. csoundCreate
2. csoundCreateMessageBuffer
3. csoundCreateMessageCallback
4. csoundPreCompile
5. csoundCompile
6. perfThread = new CsoundPerformanceThread
7. perfThread->SetProcessCallback(CsoundEngine::csThread)
8. perfThread->Play

There are two issues for HTML only performance.

First, CsoundQt never calls csoundStart, it is called implicitly by csoundCompile. For HTML only performance, this is a dummy compile. Unfortunately, this compile means that when the HTML only performance thread begins, it will immediately exit because there is no score pending. This is the most serious issue. In other words, this is a "non real time" performance that ends when the score ends.

Second, the above sequence of calls is used by CsoundQt to wire up Csound's channels and audio and MIDI drivers to CsoundQt instead of directly to the operating system. It would be best if the HTML only performance also did that but it is probably not strictly necessary.

A typical sequence of Csound API calls for HTML only performance would be:

                csound.setMessageCallback(csoundMessage);
                csound.setOption('-m3');
                csound.setOption('--nodisplays');
                csound.setOption('-odac');
                csound.compileOrc(document.getElementById('orc').value);
                csound.readScore('f 0 360\n');
                csound.start();
                csound.perform();

**Comment by gogins** [comment]
Putting in an f 0 event did not help.

I think the cause of the issue is not creating CsoundPerformanceThread in HTML only performance.  I had a different thread in the old code but now I wish to use the same CsoundPerformanceThread object in HTML only performance. I think this will do the refactoring that we need. There is probably some way of squirreling this pointer into the CsoundHtmlWrapper.

**Comment by tarmoj** [comment]
On Saturday, July 08, 2017 09:31:53 PM Michael Gogins wrote:
> I have traced through CsoundQt and now understand at least some of why the
> html-only performance is not working.
> 
Hi,

There is another problem - the options for audio driver. If one uses something else 
than  portaudio in CsoundQt (like jack, coreaudio, asio etc) the typical -odac in html 
code would not work for audio output. 

In normal csd files one can check "Ignore CsOptions" and the driver chosen in 
CsoundQt configuration is replaced.

One possible way for integration could be to open a hidden DocumentPage object 
for the csound code That one creates CsoundEngine with necessary options, the 
pointer to its csound object can be passed to CsoundHtmlWrapper and methods for 
starting/Stopping Csound could be used through the methods of CsoundEngine or 
DocumentPage.  

I plan to work on it int qthtml2 branch next week.

By the way, qthtml branch does not make sound in csd-html nor html-only files for 
me... did not dig deeper though.

I tried to have a look to the latest commits in qthtml branch but almost all files were 
completely replaced (ie all rows with -- mark and complete file again with ++ rows) -  
so it was not very informative.

tarmo

**Comment by gogins** [comment]
In the qthtml2 branch the CsoundEngine already is passed to the
CsoundHtmlWrapper. The difference is that in the qthtml branch the
CsoundHtmlWrapper uses its own thread, and I am now changing the qthtml2
branch to use the CsoundPerformanceThread.

In the qthtml branch the HTML only files do make sound for me, and in the
qthtml2 branch the CSD files with HTML also make sound for me.

Best,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by gogins** [comment]
Need to remove CSOUND object from CsoundHtmlWrapper and use only CsoundEngine as its being null can serve as an unambiguous flag.

**Comment by gogins** [comment]
I have pushed the following changes in the qthtml2 branch.

1. I have updated the CsoundHtmlWrapper to identify when Csound is initialized and when it is running to protect against calls from JavaScript that otherwise crash Csound.
2. I have changed CsoundHtmlWrapper to always use the CsoundEngine and its CsoundPerformanceThread instead of its own version of threading such as is still used in the qthtml branch.
3. I have put in logic so that csoundCompile is not called by CsoundQt for HTML-only performance,  but csoundPreCompile and the creation of the CsoundPerformanceThread object are still done in the same way in both types of performance.
4. I have made other small changes to correct the sequence of calls required to use Csound from HTML-only performances.

With these changes, both regular CSD performance, CSD performance with embedded HTML element, and HTML-only performance all basically work.

There are some crashes that need to be investigated and fixed.

**Comment by gogins** [comment]
The above comment is not correct. HTML only performance is still ending early when csoundPerformKsmps returns 2. 

Some of the crashes have been fixed, though.

**Comment by gogins** [comment]
The daemon mode (option `--daemon`) is no help.

**Comment by gogins** [comment]
I have written a C++ test program to analyze Csound API performance modes.

Scrims_qt.html runs in NW.js in real-time mode. Does it run in CsoundQt in real-time mode also?

**Comment by gogins** [comment]
I have created a test program to elucidate the details of the different Csound API performance modes and, also, to try to reproduce the problem we are having with HTML only pieces exiting prematurely from performance with csoundPerformKsmps returning 2 (score finished) when it should not. I ran this program on Linux and was not able to reproduce the problem. I am now going to try to run it with mingw64 and also with a Visual
[csound_performance_mode.cpp.txt](https://github.com/CsoundQt/CsoundQt/files/1145440/csound_performance_mode.cpp.txt)

 Studio build of the test program. The program code is attached.

**Comment by gogins** [comment]
The `csound_performance_mode.cpp` program runs identically as built on Linux, on Windows with mingw64, and on Windows as built with Visual Studio 2015.

**Comment by gogins** [comment]
I am going to try to reproduce the behavior of the CsoundPerformanceThread in my test program.

**Comment by gogins** [comment]
OK, I think I have found the problem. 

- When CsoundPerformanceThread::Perform is called _after_ csoundStart, the test program plays the test score and finished properly. 
- When CsoundPerformanceThread::Perform is called _before_ csoundStart, the test program exits performance prematurely and then CsoundPerformanceThread::Join throws an exception.

As it happens CsoundQt in HTML-only performance calls CsoundPerformanceThread::Perform is called _before_ csoundStart.

**Comment by gogins** [comment]
I have fixed the problem by not creating the performance thread in` CsoundEngine::runCsound` if the performance is HTML-only. Instead, a new `CsoundPerformanceThread` is created in the `CsoundHtmlWrapper::perform` method.

There is still an issue with the HTML view not updating rapidly enough during Csound performance.

**Comment by gogins** [comment]
https://bugreports.qt.io/browse/QTBUG-61701

**Comment by gogins** [comment]
The problem is not handling Csound messages. I commented all that out and it still hangs the Web UI.

**Comment by gogins** [comment]
https://bugreports.qt.io/browse/QTBUG-61701

**Comment by gogins** [comment]
Proposal:

1. Keep existing architecture for CSD files with embedded HTML element.
2. Declare new CsoundHtmlOnlyWrapper for HTML-only performance. The CsoundEngine will not be used at all. All Csound behavior will be controlled by the CsoundHtmlOnlyWrapper. Messages from Csound will be collected from Csound into a buffer or queue and a pure JavaScript callback can be used in the JavaScript context of the HTML page.

**Comment by tarmoj** [comment]
Sound good idea.
It seems to me, too, that html files need different approach that cannot be
realized with CsoundEngine.
But do we need different class for that? Only couple of methods (compile,
perform, stop) are different, so it is only question how and where Csound
object is created and forwarded to CsoundWrapper.
Maybe there is something I don't see now.

Tarmo

14.07.2017 16:03 kirjutas kuupäeval "Michael Gogins" <
notifications@github.com>:

**Comment by gogins** [comment]
I'm not sure where the problem really is, but I'm pretty sure it would take
more than a little work to find out. Much less work is required to create a
whole different proxy for HTML only performance. If that works, we can
create an abstract base class for the wrapper, then specialize it for CSD
performance and HTML only performance.


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by gogins** [comment]
OK, it took me about an hour to copy the existing wrapper and modify it for HTML only performance, and it works fine except that message callbacks are not handled. I will try to get that working now. They will go to a JavaScript callback in the Web page's JavaScript context for now. Later maybe we can get them into the CsoundQt console. I am going to push what I have done now.

**Comment by gogins** [comment]
Getting the Csound message to work _inside_ the CsoundHtmlOnlyWrapper was cake. Passing a JavaScript callback from the JavaScript context of the HTML page in HTML-only performance does not work because the WebChannel doesn't know how to serialize the QObject representing the callback. I can think of at least one workaround: just pass the name of the callback, then directly execute JavaScript from the host side, i.e. eval("myCallback('my csound message from the callback.');. 

But I will research callbacks using the WebChannel.

**Comment by gogins** [comment]
This is now fixed in the qthtml2 branch. It needs a little polishing and then can be merged into the main branch.

Given how the QWebChannel works, JavaScript callback objects will not pass through the Web channel and so `csound.setMessageCallback` cannot be used from JavaScript. It is stubbed out until some way around this can be found. Instead, Csound messages are printed to the regular CsoundQt message console.

For now, a static `CsoundHtmlOnlyWrapper::messageCallback_` function is called in the constructor of the `CsoundHtmlOnlyWrapper` object, and delegates to a non-static `CsoundHtmlOnlyWrapper::messageCallback` member function. This in turn passes the message to a new `passMessages` signal of the `CsoundHtmlOnlyWrapper` class. Then, when the HTML page's `CsoundHtmlView::play` method is called, the `CsoundHtmlOnlyWrapper::registerConsole` method is called, which connects the `CsoundHtmlOnlyWrapper::passMessages` signal to the console's `appendMessage` slot. This appears to work fine and without any obvious impact on performance.

**Comment by gogins** [comment]
I have pulled, built, installed, and tested the qthtml3 branch. The `Scrims_qt.html` piece now runs well in the qthtml3 branch of CsoundQt. The `Html_file_in_CsoundQt.html` piece does not run. I believe this is because of the issue I previously identified (copied from earlier comment):

1. When `CsoundPerformanceThread::Perform` is called _after_ `csoundStart`, the test program plays the test score and finishes properly.
2. When `CsoundPerformanceThread::Perform` is called _before_ `csoundStart`, the test program exits performance prematurely [...]

I am investigating to see if this is still an issue in the qthtml3 branch. It is possible that there is a call to `csoundStart` inside `csoundCompileCsdText`, which would cause the second case above. `csoundCompileOrc` does not call `csoundStart`.

**Comment by gogins** [comment]
Following @tarmoj's commit 9f2e8ea45960ad61d746f6c6d21682512cc8bcb8, I made some minor changes:

1. Call `csound.Start` in Html_File_in_CsoundQt.html.
2. Remove calling `checkCsound` in `CsoundHtmlWrapper.start`.

The following examples can all now be run after CsoundQt is first started:

1. Kung-Xanadu.csd
2. Html_FIle_in_CsoundQt.html
3. Scrims_qt.html

Strictly speaking this closes the issue of not being able to run HTML only performances in CsoundQt. 

However before closing the issue there are some other things to look at:

1. The GameOfLife3D_qt.csd example does not run. 
2. HTML only performance may run or crash if done after any prior Csound performance.

**Comment by gogins** [comment]
On second thought, since Minimal_Html_Example.csd works, forget about GameOfLife3D_qt. It's done when you can restart the four pieces and CsoundQt doesn't crash.

**Comment by gogins** [comment]
@tarmoj, I feel like we have made great progress, but I think you have taken at least one step backwards.  What I am talking about is CsoundHtmlWrapper::compile where you call CsoundEngine::prepareCsound and, in that function, call csoundCreate.

This is wrong, because you are assuming not only that the user will not already have called csoundCreate (which, in the context of CsoundQt, will usually not be the case), but also that the user will not call csoundCompile a second time, or call csoundReadScore BEFORE csoundCompile. In the case of live coding in an HTML only project, a use case that we should be able to support, that would NOT be the case.

The purpose of the JavaScript API is not to make it easy to write Csound code in JavaScript in CsoundQt or on any other platform in some new way. The purpose of the JavaScript API on ALL platforms is to behave, on ALL platforms, as much as possible the same way as does the plain C API. In the C API, csoundCompile just compiles, it does not create a Csound instance. So, in JavaScript, csound.compile should just compile.

I think we have gotten pretty close to a releaseable product here, and I agree that trying to work with CsoundEngine and CsoundPerformanceThread is the best choice for the sake of simplicity and maintainability if it can be done, but this business of "just act like the C API" needs to be fixed.

**Comment by tarmoj** [comment]
Sure this must be fixed. Can you please give some html examples to test
against. I believe it is possible to add necessary conditions. As much I
understand, whatever user wants to do (readScore, compileOrc etc) - it is
not possible if csound pointer is not there, ie csoundCreate MUST be
called. It can be left for user but typically in the currend html files I
have not seen any csound.create or similar calls.

I thought calling checkCsound in any CsoundWrappers function that user may
call first should solve this problem (as it actually is now) but maybe I
overlooked something. So please give some examples (may be just order of
different csound. calls from js console).

I hope to get to it in some hours.

Many thanks, this has been indeed a big thing to attack!

Tarmo


17.07.2017 20:35 kirjutas kuupäeval "Michael Gogins" <
notifications@github.com>:

@tarmoj <https://github.com/tarmoj>, I feel like we have made great
progress, but I think you have taken at least one step backwards. What I am
talking about is CsoundHtmlWrapper::compile where you call
CsoundEngine::prepareCsound and, in that function, call csoundCreate.

This is wrong, because you are assuming not only that the user will not
already have called csoundCreate (which, in the context of CsoundQt, will
usually not be the case), but also that the user will not call
csoundCompile a second time, or call csoundReadScore BEFORE csoundCompile.
In the case of live coding in an HTML only project, a use case that we
should be able to support, that would NOT be the case.

The purpose of the JavaScript API is not to make it easy to write Csound
code in JavaScript in CsoundQt or on any other platform in some new way.
The purpose of the JavaScript API on ALL platforms is to behave, on ALL
platforms, as much as possible the same way as does the plain C API. In the
C API, csoundCompile just compiles, it does not create a Csound instance.
So, in JavaScript, csound.compile should just compile.

I think we have gotten pretty close to a releaseable product here, and I
agree that trying to work with CsoundEngine and CsoundPerformanceThread is
the best choice for the sake of simplicity and maintainability if it can be
done, but this business of "just act like the C API" needs to be fixed.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/CsoundQt/CsoundQt/issues/227#issuecomment-315825399>,
or mute the thread

**Comment by gogins** [comment]
I will write some examples.

Best,
Mike

**Comment by tarmoj** [comment]
Another thing I noticed about changing tabs:

- if to be on a normal csd and go back to html page (or csd with html)  
Javascript reports error "qt not defined", if to go to another html page an 
then back, qt object seems to be set. 

Check, if javascript loads too early ( possible like loadingFinished condition 
or order of calls) or there is something left from previous pages that is not 
correct...

t

**Comment by gogins** [comment]
Improvements:  HTML wrapper csound.stop must call csound.Join, csound.Cleanup, csound.Reset.
Prevented multiple connections to message console.

**Comment by gogins** [comment]
Clarifications on mapping the Csound API to JavaScript:

1. `csoundCreate` is called by the host which pushes that instance of Csound into the JavaScript context with a JavaScript wrapper. All of the existing HTML5 hosts for Csound work this way. Exposing `csoundCreate` such that could write e.g. `csound_instance = new Csound();` would be possible but as far as I recall has not yet been done in any these platforms. 
2. There are intrinsic difficulties with the Csound performance thread routine and `csoundStart`. Not all platforms have implemented this in the same way. On some platforms, `csound.perform()` internally calls `csoundStart`; on other platforms, such as csound.node and now CsoundQt, it does not.
3. 

What we are dealing with here is the art of compromise. Emulating every detail of `csound.h` in the JavaScript context on all of these different platforms is, in my view, more work than I care to do. 
Another potential incomptibility is that on some platforms `csound.stop` simply calls `csoundStop`, whereas on other platforms including csound.node and now CsoundQt, `csound.stop` also joins the performance thread, cleans up the Csound instance, and resets the Csound instance. This would create problems for applications or pieces in which Csound is stopped and then, without recompiling orchestra, restarted, but it should not create problems for the kinds of pieces we are testing.
What is possible is to enable pieces that are written to use the core of the Csound API, which I have outlined above, to run just the same way on all of the Csound/HTML platforms.
I am about to add a dummy `csound.start` function to the WebAssembly API, which is one of the ones where `csound.perform` internally calls `csound.start`.

**Comment by gogins** [comment]
I am going to get HTML only tabs to simply shut off the performance when the tab changes. Then I am going to merge the develop branch into the qthtml2 branch. Then that can easily be merged back into the develop branch and this issue can be closed.

**Comment by gogins** [comment]
As I understand it the intended behavior of the tabs is that when one tab is playing and the user switches to another tab, the original tab continues to play until the user presses the play button on the current tab, at which point Csound stops playing in the original tab and starts playing in the current tab.

These are the possible cases:

1. Switch from CSD only to CSD only: works fine.
2. Switch from CSD only to CSD with HTML:
3. Switch from CSD only to HTML only:
4. Switch from CSD with HTML to CSD only:
5. Switch from CSD with HTML to CSD with HTML:
6. Switch from CSD with HTML to HTML only:
7. Switch from HTML only to CSD only:
8. Switch from HTML only to CSD with HTML:
9. Switch from HTML only to HTML only:

**Comment by gogins** [comment]
@tarmoj could you please build and test the qthtml2 branch.

**Comment by tarmoj** [comment]
I am happy to! Have been dollowing your messages and seems most likely it
works. I am back in town but can get to CsoundQt probably tomorrow.
Tarmo

29.07.2017 2:49 kirjutas kuupäeval "Michael Gogins" <
notifications@github.com>:

**Comment by gogins** [comment]
I added a stub csound.perform() to the WebAssembly module. More needs to be done here, but this is enough for now.

**Comment by tarmoj** [comment]
Hi, 

I tested qthtml2 branch on Linux and it works well!

Some things I noticed 


- CsoundQt exits always with crash
Csound tidy up: Segmentation fault

caused from console.cpp:68
setTextColor(m_textColor); 
and before that void CsoundHtmlOnlyWrapper::csoundMessageCallback:258
	passMessages(message);
Seems that csound is destroyed already when last messages are tried to sent to console. Or 
maybe something else,  you know probably better.


-  in some cases I got several messages "Initialized Csound" and many "insert_score_event: 
invalid instrument number 6" - the instrument numbers were random and non existing in my 
csd. Seemed as if something had left in some variable or buffer. Later I could not repat this 
behaviour. Output:

new alloc for instr 1:
insert_score_event(): invalid instrument number or name 7
insert_score_event(): invalid instrument number or name 6
insert_score_event(): invalid instrument number or name 7
insert_score_event(): invalid instrument number or name 6

This situation happened when I had Scrims.html as the active page on opening and then moved 
to another page.

- when to change from a non-html-including page to html (or csd with html) page kavascript 
reports: "initialize_csound error: qt is not defined" -  seems like the page gets loaded before the 
webchannel is establised in such case (but only if the previous pages was non-html, ie 
CsoundHtmlView was showing and emptu Url). I investigated how to reset the channel, 
unregister object etc but no success yet. This is a bad problem that should be solved. in WebKit 
there is a signal  javaScriptWindowObjectCleared that could be used to add JS object, but in 
WebEngine I have not found similar solution yet.

- I would really love to have an oportunity to use CsoundQt options for platyback -  for 
example I usually use jack for CsoundQt work, but html pages usually  have just -odac option 
in their page. I added this possibility to qthtml2 -  please review and revert the commit, if 
needed.
I added also a protective acondition to CsoundQt::play to return, if the file is .html.

I made some changes to qthtml3 branch as well to use temporary files for compilation and now 
it works nicely, too. Please try it out, if you have time. Nevertheless I tend to prefer qthtml2 for 
now to go on since qthtml3 has quite much messy code and and several workarounds that 
might cause different drawbacks. I think it is good to keep it still existant if it turns necessary to 
use the CsoundEngine approach (like integration with CsoundQt Widgets, internal MIDI etc). 
The biggest problem of qthtml3 branch is now that if some error happens during 
CsoundPerformanceThread playback, CsoundQt freezes and cannot sop the thread properly. 
This could be solved, though, I believe.

Tarmo

**Comment by tarmoj** [comment]
I think I found the reason for "qt is not defined" error or at least a way to 
work around this - 

the problem was in CsoundHtmlView:clear() -  setting empty URL probably 
disconnected webchannel. Now clear() hides htmlView that will be made visible 
again when new html part is loaded.

Pushed to qthtml2 part.

If this seems OK, I think the implementatios is quite ready.

Perhaps you could have another look over the code, clean what need to be 
cleaned, let's make some more tests and merge it to develop branch.

If you don't mind, I will do the merge - as I know more about the recent 
changes in develop branch.

Next I will set the version to 0.9.5-beta, make test binaries and announce the 
version to be tested for users. Let's hope we can manage with that in coming 
week -  from next Saturday I will be away from town again.


tarmo

**Comment by gogins** [comment]
Thanks for your work. I will test it today. I'm fine with you doing the
merge.

Best,
Mike

On Jul 30, 2017 6:22 AM, "tarmoj" <notifications@github.com> wrote:

I think I found the reason for "qt is not defined" error or at least a way
to
work around this -

the problem was in CsoundHtmlView:clear() - setting empty URL probably
disconnected webchannel. Now clear() hides htmlView that will be made
visible
again when new html part is loaded.

Pushed to qthtml2 part.

If this seems OK, I think the implementatios is quite ready.

Perhaps you could have another look over the code, clean what need to be
cleaned, let's make some more tests and merge it to develop branch.

If you don't mind, I will do the merge - as I know more about the recent
changes in develop branch.

Next I will set the version to 0.9.5-beta, make test binaries and announce
the
version to be tested for users. Let's hope we can manage with that in
coming
week - from next Saturday I will be away from town again.


tarmo



On laupäev, 29. juuli 2017 17:27.47 EEST Michael Gogins wrote:
> I added a stub csound.perform() to the WebAssembly module. More needs to
be
> done here, but this is enough for now.


—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/CsoundQt/CsoundQt/issues/227#issuecomment-318892256>,
or mute the thread

**Comment by gogins** [comment]
Your latest commit builds and runs on Ubuntu 16.04 and Windows 8/mingw64.
There are sometimes crashes on exit and rarely crashes on other actions.
Switching from tab to tab, lightly tested with CSD only, CSD with HTML, and
HTML only, seems to work.

Best,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by tarmoj** [comment]
Built on OSX, also crash on exit.

I found the reason -  passMessage() in CsoundHtmlOnlyWrapper was connected to console but in closing that one was destoyed before the signal arrived. Added a condition that controls it. Now seems fine, works also nicely on OSX.

I consider the issue solved and close it.

CONGRATULATIONS!!!

tarmo

**Comment by gogins** [comment]
Congratulations to you as well!

Have you merged this yet?

Best,
Mike

**Comment by tarmoj** [comment]
No,

Not yet, tonight or tomorrow.

T

31.07.2017 1:16 kirjutas kuupäeval "Michael Gogins" <
notifications@github.com>:

> Congratulations to you as well!
>
> Have you merged this yet?
>
> Best,
> Mike
>
