### ISSUE TITLE
Record button on OS X (10.10.5) still not recording properly

### ISSUE THREAD

**Issue by boonier** [CsoundQt/CsoundQt#230]
It creates the file, but it is empty. It's like the file doesn't get closed and isn't completed.

On latest 0.9.3

**Comment by tarmoj** [comment]
Hi,

works here on OSX 10. 11.3. Can you give some more information -  I believe 
your Csound version is 6.08 from the latest installer? Have you built Csound 
perhaps yourself and some leftovers from an older build are somewhere?

Can you send prehaps the csd you were trying it with? What are your  Realtime 
Audio  settings?

I am not sure if I get to a machine with OSX 10.10 to test myself but I will 
keep it in mind to try, if possible. Waiting for your information!

tarmo

**Comment by boonier** [comment]
Hmm so many variables! Yes so it's latest Csound 6.08. I've never built Csound on this machine, or ever in fact. 

Here's the csd: https://www.dropbox.com/s/cf78krgp8fkzjzs/testtest.csd?dl=0

And the settings: https://www.dropbox.com/s/yz4w6gb6uek4d8c/settings.png?dl=0

Might it be that I have a set of dirty preferences lying around from a previous CsoundQT?

**Comment by tarmoj** [comment]
Hi, I tested your cod with similar settings as yours (expect the exact MIDI device but it does not matter) on a OSX10.10.5 machine and the output file on pressing "Record" is produced correctly.
It is good idea to move the old settings file away and see if it helps. The settings file should be situated in 

<your home/Library/Preferences
and the file is called
com.csound.qutecsound.plist

You can try to open the CsoundQt container in Applications (show contents), navigate to the Contents/MacOs folder and run the CsoundQt binary in terminal to see if there is any useful information.

Otherwise no idea for now...

**Comment by boonier** [comment]
Hi thanks. On further tests, it does complete the record, but only if stop is pressed before the score finishes. 

If the Record button is pressed and the score is allowed to finish, then the file doesn't play. 

Does this makes sense?

Cheers

**Comment by boonier** [comment]
From terminal:

```
CsoundQt::play()...
virtual_keyboard real time MIDI plugin for Csound
0dBFS level = 32768.0
--Csound version 6.08 (double samples) Nov 23 2016 
[commit: a1159a1e12a1095c4607f7162c44b196f5143959]
libsndfile-1.0.25
csound
-b64
-B512
-+rtaudio=auhal
-odac
--env:CSNOSTOP=yes
/Users/boonier/Dropbox/Csound/testtest.csd
start recording (32-bit samples): /Users/boonier/Dropbox/Csound/testtest.csd-000.wav
Recording stopped.
CsoundEngine::stopCsound() joined
Recording stopped.
```

**Comment by tarmoj** [comment]
Hi,

Although your file works perfectly on Linux, I am getting similar result 
(recorded file is empty) or sometimes crash on OSX 10.12.3. I am currently 
changing the development virtual machine and can't get CsoundQt to build yet. 
I will investigate as soon I get to that point.

Thanks for the report!

In the meanwhile you can make experiments - in configuration your buffer size 
-b was set to 64 but ksmps to 128. See what happens if you increase -b and -B 
10 say 512 / 1024. You can also try out portaduio as rtaudio  module and see 
if that makes any change (I believe not...)

tarmo

**Comment by tarmoj** [comment]
Now recording works fine when I have built CsoundQt against Sound 6.09 beta. The release candidate is up on:
https://github.com/CsoundQt/CsoundQt/releases/download/0.9.4-rc1/CsoundQt-d-py-0.9.4-rc2.dmg

I have not tried, how it works with Sound 6.08 but if you have a chance, test it. Sound 6.09 including CsoundQt 0.9.4 will be out next week, too.

**Comment by boonier** [comment]
👍  great! Look forward to trying it out and testing. Thanks for your hard work.
