### ISSUE TITLE
Crash when re-evaluating section/selection that contains a macro

### ISSUE THREAD

**Issue by boonier** [CsoundQt/CsoundQt#248]
This might not be a CsQT bug and more a specific Csound thing.

I'm guessing that macros aren't referenced when recompiling on the fly?

CsQT 0.9.4.1
OSX 10.10.5

**Comment by tarmoj** [comment]
Hi,

Thanks for the report! And yes, it is a Csound bug. Can you open a ticket
in Csound issue tracker, all feedback is valuable! It is logical that
orchestra foes not know macro names since it is the preprocessors job to
parse and substitute them but Csound should not crash on that and I am sure
the developers want to know about that.

Tarmo

08.11.2017 16:01 kirjutas kuupäeval "Si Mills" <notifications@github.com>:
