### ISSUE TITLE
widows installer

### ISSUE THREAD

**Issue by Reaper10** [CsoundQt/CsoundQt#249]
could someone make widows installer? I wanted learn your software, but i can't get it to run from zip.

**Comment by tarmoj** [comment]
Hi,
This is maybe not so obvious (I should add some kind of check and warning): have you installed Csound first? CsoundQt is just a frontend and requires Csound to be installed:

http://csound.com/download.html

CsoundQt is also included in the packages, but not yet the newest one.

Please report back if this was the issue. Otherwise please provide more information -  do you get any error messages, complaint about missing libraries etc?
