### ISSUE TITLE
macOS key command conflicts with new tab switching on 0.9.5

### ISSUE THREAD

**Issue by boonier** [CsoundQt/CsoundQt#257]
Hi I can't add a # for typing macros, as CsoundQT intercepts the key command and switches tabs instead. Am I missing something in the Keyboard shortcuts to change the key combo for switching tabs so as to not interfere?

Alt+3 on a mac is universal for #

Thanks

**Comment by tarmoj** [comment]
Thanks for the report!

Yes, it seems a bottle-neck right now - Currently Alt-number is hardcoded
to change tabs. Seems that on Mac it should be cmd+number. I am sitting by
a Mac now and here Shift+3 is # ? It can be different on different layouts.
Can you let know which Mac OS version you are using and which keyboard
layout?

Anyway, it must be fixed, I will get to that as soon I can (tonight or
tomorrow), hopefully you will be ready for testing.


tarmo


2018-01-17 13:58 GMT+02:00 Si Mills <notifications@github.com>:

**Comment by tarmoj** [comment]
Hi,

I leaved still Alt+<number> for changing tabs but rewrote the code a bit to be more cross-platform. It probably does not change anything for you but I added an option in Configure -> Editor -> Enable Tab Changing shortcuts (or how was it called...). You need to close and reopen CsoundQt to make it effect. 
Pleaes try:
http://tarmo.uuu.ee/varia/failid/cs/CsoundQt/CsoundQt-0.9.5.1-MacOS.dmg

I have not tested it on a phisical Mac, I am developing on a rented remote Mac over internet, so please let me know.

And for interest -  what kind of Mac and keyboard layout it is since usually it is Shift+3 for # - so I know if it is a common problem (nobody reported it!) or on some strange case.

tarmo

**Comment by tarmoj** [comment]
Hi,

Did you have chanve to try? Should I replace the .dmg file in release page?

t

**Comment by boonier** [comment]
@tarmoj So sorry I didn't see this. I'll try testing as soon as I can. On my UK/British keyboard layout # is Alt+3. Shift+3 gives me £

**Comment by boonier** [comment]
@tarmoj Just tested the new build and the new setting brings back the key command (but loses the tab switching). Could you add the tab switching entries in Keyboard Shortcuts? 

So for tabs I would personally use Cmd+Shift+[number] and use Cmd+[number] for raising/hiding the panels.

But I think the new build is good for release for hot fix. Many thanks!

**Comment by tarmoj** [comment]
Hi, I changed this to Control + number on Mac in 0.9.6. Hope it works.
