### ISSUE TITLE
Console is blank whilst running csd

### ISSUE THREAD

**Issue by boonier** [CsoundQt/CsoundQt#276]
When testing the websocket example, for some reason the console clears and doesn't log anything while running, but when Csound is stopped, all the printed values appear.

Latest 0.9.6-beta3 on macOS 10.13.6

**Comment by boonier** [comment]
Another issue maybe related or not. When quiting CsoundQT after running that example, the app hangs and I have to force quit.

could the websocket opcode be the culprit?

cheers!

**Comment by tarmoj** [comment]
Hi,

Here (OpenSuse Linux, Csound 6.13 from git, CsoundQt 0.9.6-beta3) the
websocket example works as expected. Since it depends on external library
(libwebsockets), there might be some dependency problem or version mismatch
on MacOS. Also make sure that nothing is listening already on port 8888 (or
change the port in csd). If the same problem happens in terminal, please
report it in the Csound list, if someone can confirm.

Greetings,
tarmo

Kontakt Si Mills (<notifications@github.com>) kirjutas kuupäeval K, 26.
juuni 2019 kell 12:51:
