### ISSUE TITLE
Win10 Crash

### ISSUE THREAD

**Issue by m3t4lp0w3r** [CsoundQt/CsoundQt#278]
Hi there I am new here and I will appreciate your help.
I am new in coding for audio and i found something really strange:
I wrote this code with a loop inside the score but when i try to run it in windows 10 using Cabbage 2.1.05b or in CsoundQt latest version i get a Crash. 
I tried to run also on Cabbage an Qt for Mac and it works, Am I missing something? It's so confusing.
Thank you for your help! 
<CsoundSynthesizer>
<CsOptions>
-odac
;-o Ambientemod.wav -W
</CsOptions>
<CsInstruments>

sr = 41000
kr = 410
nchnls = 2
0dbfs = 1
instr 1
aR,aL loscil 1,1,1,1,2
aS poscil p4,p5,2
outs aL*aS,aR*aS
endin
instr 2
aR,aL loscil .5,1,1,1,2
outs aR,aL
endin

</CsInstruments>
<CsScore>
f1 0 0 1 "Ambiente.wav" 2 0 0
f2 0 [2^16] 10 1
i2 0 5
{10 loop
;i1 0 1 .01 10
i1 [3+((~*1)*50)] [(~*$loop)+10] .8 [15+(~*($loop*100))] 
}
</CsScore>
</CsoundSynthesizer>

**Comment by tarmoj** [comment]
Hi,

I suspect it is a porblem in Csound, not CsoundQt that is mere frontend. Please run the code in terminal (Run in terminal from menu or use cmd.exe to run 
csound yourcsd.exe 
)

If it works, the problem is in CsoundQt, otherwise please report in the Csound mailing list or issue tracker.

Thanks for the message, anyway! Reports are always welcome!

tarmo
