### ISSUE TITLE
Future CsoundQT and Python support

### ISSUE THREAD

**Issue by boonier** [CsoundQt/CsoundQt#280]
Why does the latest Csound package (6.13) from the web site not ship with python support (I grabbed it from this repo releases page)? I read in a post somewhere that no one uses pythonQT, but I can't seem to find any evidence to support that. Is HTML support superseding it from now on? I've only just started using it to build complex interfaces but I wonder whether I'm travelling down an eventual dead-end...

**Comment by tarmoj** [comment]
Hi,

You can get the version with pythonqt from  CsoundQt release page, see link
from release announcement.
The problem is that PythonQt built on Mojave did not work on older MacOS.
On older OS you could stick with CsoundQt 0.9.5 or build yourself.
Hope it  clarifies the situation,
Tarmo

R, 19. juuli 2019 10:43 Si Mills <notifications@github.com> kirjutas:
