### ISSUE TITLE
exitnow is not working in csoundqt6

### ISSUE THREAD

**Issue by pmanionatacm** [CsoundQt/CsoundQt#290]
Hello,
Csound version 6.13 (double samples) Jul 28 2019
Mac OS X 10.13.6 (High Sierra)
the exitnow opcode does nothing when run in csoundqt. If the code is run from the command line my code exits correctly. Jim Aiken had reported this earlier on. It is still broken.
Thank you!

**Comment by tarmoj** [comment]
Hi,

Yes, it is more complex within CsoundQt as Csound runs as one process of CsoundQt and I am not sure what exitnow actually does in the lower level. I could find a way how to overcome it from CsoundQt-s code right now. So far I suggest to use 
scoreline "e" (or scoreline_i "e" ) 
instead of exitnow.

tarmo

**Comment by pmanionatacm** [comment]
Thank you for the tip: scoreline "e", ktrig worked well
