### ISSUE TITLE
Fails to run on xenial

### ISSUE THREAD

**Issue by probonopd** [CsoundQt/CsoundQt#291]
Thanks for providing an AppImage. 

For compatibility with all still-supported Ubuntu releases, please build on a system no newer than the oldest still-supported LTS release (xenial at this time). Thanks.

```
`/lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /run/firejail/appimage/.appimage-9284/usr/bin/../lib/libpng16.so.16)`
```

Reference:
https://github.com/AppImage/appimage.github.io/pull/1879

**Comment by tarmoj** [comment]
Yes,
 I am aware of that. This was an experimental build. When I will have
everything figured out, i will set up a VM with  Ubuntu Xenial.
Thanks for the report, anyway!
Tarmo

L, 18. jaanuar 2020 09:49 probonopd <notifications@github.com> kirjutas:

**Comment by probonopd** [comment]
Hi Tarmo, thank you very much. If you don't want to build on your local machine, you could also consider to use a service such as Travis CI.

**Comment by probonopd** [comment]
Here is an example for how to do it on Travis CI:
https://github.com/probonopd/linuxdeployqt#using-linuxdeployqt-with-travis-ci

**Comment by tarmoj** [comment]
Hi,

Thanks, it can turn useful! For now CsoundQt is not built on Travis/AppVeyor but I agree it might be worth go through it and make it happen once. 

What concern AppImage build, I do it now on a Ubuntu 16.04 virtual machine.
Here is the script:
https://github.com/CsoundQt/CsoundQt/blob/develop/make_appdir/make-appimage-linux.sh

A test build that includes both CsoundQt and Csound is up on:
https://tarmo.uuu.ee/varia/failid/cs/CsoundQt/CsoundQt-0.9.8.2-x86_64+Csound-6.14.0.AppImage

This misses some dependencies of Csound plugins (liblo, libstk libportmidi), which I will fix, otherwise seems to work well.
Please try!

tarmo

**Comment by probonopd** [comment]
This one works. Thank you very mcuh @tarmoj
