### ISSUE TITLE
Apple AirPods not working/recognized

### ISSUE THREAD

**Issue by pmanionatacm** [CsoundQt/CsoundQt#294]
Hello,
I cannot get my AirPods to work in CsoundQt. Perhaps it is some obvious error/misunderstanding on my part.

Mac OS X version 10.15.2 - Catalina
CsoundQt version 9.6
Csound version 6.13
Everything works if I use the command line. Using the command line I enter: csound -odac1 music.csd and I can hear the music in my AirPods.

In CsoundQt no amount of fiddling with with the configure dialog-the AirPods do show up correctly in the configure dialog - or entries in \<CsOptions\> will work. The AirPods are listed correctly in the configure dialog as dac1 but when I press the run button I get the following error: 

PortAudio V19-devel (built Feb 12 2010 09:42:54)
   0: adc0 (Built-in Microph [Core Audio])
   1: adc1 (Patrick’s AirPo [Core Audio])
PortAudio: selected input device 'Patrick’s AirPo'
 *** PortAudio: error: -9998: Invalid number of channels
Failed to initialise real time audio input

**Comment by joachimheintz** [comment]
hi -

i cannot really help with this particular issue as i have neither a mac 
nor airpods, but some possibilities come in my mind which you might try out:

1. there is a new csound version which includes a new csoundqt version 
(0.9.7):
https://github.com/csound/csound/releases/download/6.14.0/Csound6.14.0-MacOS_x86_64.dmg
2. usually it works better if you choose your audio devices in the 
system preferences and then in csound(qt) only have -odac (rather than 
-odac1 or similar).

hope this helps -
	joachim

**Comment by tarmoj** [comment]
Hi,

Same here -  I have not way to test, some things that you can try:

- if you say it works from command line, you can just disable the CsoundQt
options Configure -> Realtime audio, uncheck "Use CsoundQt options". Does
it work then?

-  From the following report I assume the problem is in  input (I guess the
headset has 1 input channel but Csound expects 2):
PortAudio V19-devel (built Feb 12 2010 09:42:54)
0: adc0 (Built-in Microph [Core Audio])
1: adc1 (Patrick’s AirPo [Core Audio])
PortAudio: selected input device 'Patrick’s AirPo'
*** PortAudio: error: -9998: Invalid number of channels
a) try to disable input (set to none in Configure)
b) set number of input channels in you csd:

nchnls_i = 1


tarmo

Kontakt joachimheintz (<notifications@github.com>) kirjutas kuupäeval T, 4.
veebruar 2020 kell 13:20:

**Comment by pmanionatacm** [comment]
Thank you for the suggestions guys. I did get it to work by unchecking the "Use CsoundQt Options" in the configure page and adding "-odac" (not odac1) in the \<CsOptions\> section. When the "Use CsoundQt Option" box was checked I could not get any selection to work. Thank you again!

**Comment by pmanionatacm** [comment]
I just downloaded and installed the csound 6.14 and CsoundQt 9.7 and the "Use CsoundQt Options" button is now working correctly. Thanks guys!
