### ISSUE TITLE
Cut/Copy isn't placing content in the clipboard

### ISSUE THREAD

**Issue by candlesayshi** [CsoundQt/CsoundQt#295]
[Windows 10 - CsoundQt 0.9.7] Copy and paste doesn't seem to be working as expected. Copying or cutting from CsoundQt's editor isn't putting anything in the clipboard. Cutting removes the highlighted context though still doesn't put it in the clipboard. Pasting context copied from outside CsoundQt into the editor still works however.
In looking through the issues it appears this was a past issue. I don't believe it occurred in the version I had previously installed. Also, in the version on my Linux machine [0.9.4 from the Ubuntu repositories], this issue also doesn't occur.

**Comment by tarmoj** [comment]
Thanks for the report!
And I am very sorry and puzzled to hear that! Nothing has changed in the
code in that respect...

I will try when I get to a Windows computer. Meanwhile you can roll back to
CsounQt 0.9.6, there is not so much change for Windows between these
versions,

Tarmo

T, 11. veebruar 2020 19:44 candlesayshi <notifications@github.com> kirjutas:

**Comment by tarmoj** [comment]
Hi!

I finally got to check it out. Actually I cannot reproduce - copying to and from CsoundQt works for me on Windows 10. Maybe it happens when you have worked for a while? I tried rather shortly.

I used the CsoundQt built locally  and also the one from installer of Csound 6.14 - both worked as expected.

Can you  try and test more and descibe on which situation it exactly happens, to which porgram you copy, can you repeat the situation etc - maybe you can guess and  suggest the cause yourself?
Can you try on another machine? Completely remove Csound6_x64 folder and try again?

Best!
tarmo

**Comment by candlesayshi** [comment]
This morning I uninstalled everything and reinstalled the full Csound 6.14, and now I can also confirm that it's now working as expected. My _guess_ is that it had something to do with upgrading from 6.13 to 6.14 and the respective CsoundQt versions with it, because there were other library issues I had with Csound itself. However, that's not a problem anymore either. I'll try and see if I can play with that to try and reproduce it and I'll come back if something comes of it

**Comment by candlesayshi** [comment]
Days later, I've been trying on and off and I still just can't reproduce this bug again. I'm inclined to believe it was an isolated thing, or perhaps even something I did on my own and can't remember or understand what I did. Because the software seems to work absolutely fine and there aren't any other recent reports on it and it's something that would have been immediately noticeable. Going to close this report and keep an eye on it, but it seems to be fine.
