### ISSUE TITLE
Problem with Recording the codes

### ISSUE THREAD

**Issue by Atamusic1988** [CsoundQt/CsoundQt#301]
Hi dears,
I have a problem with Csoundqt's record option.
When I record my codes، Csoundqt provides a Wav file which is not played at all. I have manipulated many times the sound card outputs, but nothing has changed. 
Thank you for helping me in advance.
Regards,
Ata

**Comment by tarmoj** [comment]
Hi,

Please always provide -  platform, version of CsoundQt, version of Csound.
Can you open the wav file in some editor (like Audacity), what do you see?
Is there anything suspicious in the console output? Can you hear the output
otherwise?

Greetings,
tarmo

Kontakt Atamusic1988 (<notifications@github.com>) kirjutas kuupäeval T, 17.
märts 2020 kell 14:18:

**Comment by Atamusic1988** [comment]
Thanks for your reply dear tarmoj,
It's very strage to me. After your comment, I opened the Wav file in StudioOne software and I saw that it can play it correctly and I opened it with KMPlayer and I saw it can too. I don't know why should (Windows media player) doesn't run the Wav file correctly!!!
Do you know buddy?

**Comment by tarmoj** [comment]
Hi,
It might be due to the bitrate or samplerate is soemthing different than usual 44.1KHz/16 bit, might be that Windows Media Player has difficulties opening such files.

I am glad it worked out!

Next time it would be perhaps be more appropriate to use first the mailing list for asking, 
https://sourceforge.net/projects/qutecsound/lists/qutecsound-users
 it is not exactly an issue report case (although might have been! Thanks for report anyway!)

Best,
tarmo
