### ISSUE TITLE
display widget in "newlook" branch does not show anything

### ISSUE THREAD

**Issue by joachimheintz** [CsoundQt/CsoundQt#303]
i think this has already been reported; i just wanted to make sure it is on the list.
i cannot see any display, for instance with the Examples > Widgets > Display.

**Comment by joachimheintz** [comment]
i should add: this is with today's git, branch newlook, on linux.

**Comment by tarmoj** [comment]
Hi, thanks for the report!

Sorry, it was fixed in branch newlook2, I merged it now to newlook and
pushed to git - please try again.
I think soon we should merge newlook to develop and continue from there.
My idea was that maybe it is good to have both parallel for a while if
someone wants to compare, but maybe it is not necessary.

tarmo

Kontakt joachimheintz (<notifications@github.com>) kirjutas kuupäeval K, 8.
aprill 2020 kell 11:55:

**Comment by joachimheintz** [comment]
yes i think merge is good now.  thanks-
  j
