### ISSUE TITLE
FLTK no longer working on the Mac

### ISSUE THREAD

**Issue by csounder** [CsoundQt/CsoundQt#305]
Sadly, when running any FLTK instruments in CsoundQt, all that appears are blank panels with no test, no sliders, checkboxes, or knobs

**Comment by joachimheintz** [comment]
what happens when you push "Run in Term" rather than "Run"?

**Comment by tarmoj** [comment]
Hi,

I am afraid it is the situation of Csound on Mac. From another discussion
(aboust CsoundQT 0.9.8 release candidate):

---
Quoting V. Lazzarini:

"

Unfortunately, the FLTK library doesn’t play well with the MacOS
objective-c graphics.
In this system, FLTK is used with no threads, which might explain the
behaviour, as
every time you touch the interface, the audio thread is interrupted
causing the
clicks or the sound to stop. Threads in FLTK cause Csound to crash on MacOS
so that’s why they are not used.

Maybe it’s possible to make them work, but I do not think any of us core
developers
will be  spending time trying to hack FLTK to behave. If anyone wants to
do this, they’re
welcome.

---

Sorry. So, can you think of rewriting your interface in some other way
(CsoundQT widgets, html -  that is supported in CsoundQt too, Cabbage,
independent UI (why not FLTK) and communicate with csound over UDP
messages, CsoundRemote (write an UI in QML, it uses also UDP connection))
-  depends what suits best with your experience and workflow.

If you wish, please continue the discussion in CsoundQt maining list.

Best!
tarmo

tarmo



Kontakt joachimheintz (<notifications@github.com>) kirjutas kuupäeval P,
17. mai 2020 kell 11:48:

**Comment by csounder** [comment]
So... about FLTK on the Mac...

I have always been telling CsoundQt to "run in terminal"
- but I will also try pushing the Run in Terminal Button too

In the terminal you get

csound -odac
/Users/dB/Dropbox/2day/Csound-FLTK_test/Cs-FLTK-McCurdy-table_tablei_table3.csd

0dBFS level = 32768.0

--Csound version 6.14 (double samples) Jan 26 2020

[commit: 0ce67f7c105ed2aee98d0e7f43558d62357c769b]

libsndfile-1.0.28

UnifiedCSD:
/Users/dB/Dropbox/2day/Csound-FLTK_test/Cs-FLTK-McCurdy-table_tablei_table3.csd

STARTING FILE

Creating options

Creating orchestra

closing tag

Creating score

rtaudio: PortAudio module enabled ...

using callback interface

rtmidi: PortMIDI module enabled

opcode changed deprecated

sorting score ...

... done

displays suppressed

0dBFS level = 1.0

orch now loaded

audio buffered in 1024 sample-frame blocks

PortAudio V19-devel (built Feb 12 2010 09:42:54)

   0: dac0 (Built-in Output [Core Audio])

   1: dac1 (Soundflower (2ch) [Core Audio])

   2: dac2 (Soundflower (64ch) [Core Audio])

   3: dac3 (Modulince [Core Audio])

   4: dac4 (AirBeamTV  [Core Audio])

PortAudio: selected output device 'Built-in Output'

writing 2048 sample blks of 64-bit floats to dac

SECTION 1:


and a couple of blank FLTK panels appear
_____________________________________________
*Dr. Richard Boulanger*
Professor of Electronic Production and Design
Professional Writing and Music Technology Division
Berklee College of Music

**Comment by csounder** [comment]
When I hit Run in Term - nothing appears in the console
When I hit Run - nothing appears in the console
- this is with CsoundQT 0.9.7 and with CsoundQt 0.9.8-rc1-1

The blank panels appear when you run from the CommandLine in the Terminal.

Note that these tests today have been with MacOS Catalina - 10.15.4
_____________________________________________
*Dr. Richard Boulanger*
Professor of Electronic Production and Design
Professional Writing and Music Technology Division
Berklee College of Music

<https://www.facebook.com/richard.boulanger.58>

**Comment by gesellkammer** [comment]
FLTK is not supported on mac

**Comment by csounder** [comment]
News to report here.  When building from sources, with brew install --HEAD csound, the FLTK opcodes on the Mac do work again!  And so, FLTK does seem to be suported on the Mac.

**Comment by gesellkammer** [comment]
We test csoundqt against the latest release of csound. Until FLTK is supported in the released version of csound I would still argue that FLTK is not officially supported. But it's nice to hear that it is possible at all.

**Comment by csounder** [comment]
So Eduardo,

I hope that you can appreciate the irony here.
- the latest release of Csound uses CsoundQt 0.9.7 - which you have now
told me to "stop" reporting bugs about.  And so, in one case you are
telling me - everything we do relates to the release version, and in the
other case you are telling me - don't tell us anything that is wrong with
the release version.

Sadly, the first impression and the first encounter and the first
experience is often the most important and so...Picture this:

My classes begin next week at 9 am on Tuesday morning. They will download
and install Csound.dmg with CsoundQt 0.9.7
- and the first thing that they/we run is Xanadu - because it sounds
fantastic and what do they see, a button that doesn't work or a text that
doesn't fit.  No big deal.  I often then say, hey let's download the latest
Beta version of CsoundQt - 0.9.8 rc-1-1. And I show them all the cool new
display features and widget features and then I say... let's make sure that
MIDI is working and check out PipeSynth or SimpleFM ... (now they typically
have not brought a MIDI keyboard to the first class, but this might be
different as I start next week online...)

- oh no... the MIDI keyboard appears, but the whole row of buttons goes
black and they can barely see any of the buttons.

And so... I say, oh.. play the synth - cool right... change the presets...
cool-sounding right... let's do some MIDI learn - awesome right?  Oh, we
can't see the buttons to try another instrument... don't worry, that's
nothing - it's Beta... let's relaunch the app and maybe not use MIDI for
now...

And one or two students drop the class in a day... because there are
seemingly so many "issues" with Csound and they just want to make sounds
and make music and take advantage of the power of the universal ultimate
synth and DSP tool from MIT.

I would argue that the power and value of Csound is that it connects the
past to the future and that it preserves the past while empowering,
supporting, and helping to invent the future.  And I thank you and Tarmo
and Steven and Rory and John and Victor and Michael, and Francois, and all
the developers for the innovation that you bring.

PS: Don't lose those great Python examples in the 0.9.7 Python version of
CsoundQt.

PPS: Sadly, there are all those fantastic older FLTK instruments and models
that are now, I get it, an "issue" with the Mac.  But wait... I build from
sources, and they all do run as they did in the past - and so... hmm. And,
they run from either 0.9.7 or 0.9.8 rc1-1. (Which I think might be happy
news to know about and discover. Guess not. Oh well. Learning to let go.)

*Dr. Richard Boulanger*

Professor of Electronic Production and Design

Berklee College of Music

Professional Writing and Music Technology Division

Office: 1126 Boylston St., Suite 201 (EPD), Suite 208 (Boulanger)


facebook: https://www.facebook.com/richard.boulanger.58

about: http://www.boulangerlabs.com/#about

about: http://www.csounds.com/community/developers/dr-richard-boulanger/

music:
http://www.csounds.com/community/developers/dr-richard-boulanger/dr-richard-boulanger-music/

Boulanger Labs - http://boulangerlabs.com

The Csound Book - http://mitpress.mit.edu/books/csound-book

The Audio Programming Book -
http://mitpress.mit.edu/books/audio-programming-book

**Comment by gesellkammer** [comment]
> I build from
sources, and they all do run as they did in the past - and so... hmm. And,
they run from either 0.9.7 or 0.9.8 rc1-1

The course of action here is evident: ask the csound maintainers to make a new build and sort out the problems with fltk. It has been asked before in the mailing list.
Regarding bug reports about 0.9.7: please test the same thing in 0.9.8 and report afterwords.

**Comment by tarmoj** [comment]
Hi,

Well, actually 0.9.8 is not out yet, it is still in release candidate.
Although it is very important to get more people to test the latest build, ALL bug reports are always welcome.

Best!
tarmo

**Comment by joachimheintz** [comment]
hello all -

i would like to add my opinion about the examples here.  and about the 
discussion.

1. the first responsability for an example is at the author of the 
example.  so if someone is telling me: "joachim, i checked your example 
..., i did this and that, and this and that happend (not)" --- then i 
would say "thank you, i will test and try to fix, if i can reproduce the 
issue."

2. if there are examples whose author is not available (like in Xanadu), 
the possible approaches are:
a) to send a fix in a pull request.
b) to send a fix in email or similar.
c) to describe what is happening and which might be the problem.
d) just to say "it is not working".
the reaction of tarmo, eduardo, me or anyone who might want to 
contribute, will be:
ad a): immediate merge.
ad b): should also be done quick.
ad c): it depends on our time and the report.
ad d): same, but motivation is certainly less.

3. bug reports are very much welcome.  i agree with tarmo that it does 
not really matter which version.  if it is fixed meanwhile, we can say: 
already fixed.  but no bug report can expect to be fixed until whatever 
date.

4. what a bug report can expect is to be answered in a reasonable time 
and in a polite way.  what the developer can expect is to work without 
any pressure.  we are not a company in which anyone gives orders.

i think we are all here because we use csound and csoundqt in many ways 
(for our music, in teaching etc).  and also because we want to treat 
ourselves with respect and acceptance.  aceeptance from both sides: from 
developer to user, and user to developer.

conflicts and frustrations are ok, but it would be more fun to see them 
without aggressions.

	joachim
