### ISSUE TITLE
INF delay time error

### ISSUE THREAD

**Issue by Luissssss** [CsoundQt/CsoundQt#334]
Hi guys, this is a problem on my synth from a lot of time: the synth stop playing when it occurs this error and this is the console's message.

<img width="726" alt="Schermata 2020-08-03 alle 12 09 50" src="https://user-images.githubusercontent.com/17232722/89176685-46e77b00-d58a-11ea-99a7-2edc4f43228b.png">

This is the line 728:

<img width="726" alt="Schermata 2020-08-03 alle 13 09 36" src="https://user-images.githubusercontent.com/17232722/89176863-9d54b980-d58a-11ea-995e-c28ed8cb412f.png">

This error occurs when the delay time, managed from a slider widget, is setted at the minimum (0.01 sec) or near. 
Really hope someone can help me!! best regards
Luis

**Comment by Luissssss** [comment]
I've also tried with deltap, deltapi, deltapx etc opcodes but nothing... the synth is playing for about a minute and then it stops playing, if setted with the minimum delay time

**Comment by tarmoj** [comment]
Hi,

this definitely does not seem as a bug in CsoundQt, nor in the core Csound, too, I think. 
I guess better place to discuss this problem is Csound mailing list.

The error message "INF delaytime" indicates that  adeltime1 gets out of acceptable, probably  kdeltim1 gets too small and the interpolation reaches 0 at some point. Try increasing the minimal possible delaytime in the slider and you may need to add 
printk2 kdeltim1
to make sure what are the actual values before interpolation.
or 
adel1 limit adel1, 0.001, 1 ; or something


tarmo
