### ISSUE TITLE
Windows 10 Copy & Paste not working

### ISSUE THREAD

**Issue by frmaurer99** [CsoundQt/CsoundQt#345]
I am trying to copy and paste lines of code in the CsoundQT editor but neither Ctrl+C - Ctrl+V not selecting Copy and Paste from the menu works.
Tried highlighting code and pressing Ctrl+C does not copy code to clipboard. Pasting code from notepad to CsoundQT with Ctrll+V does work.

**Comment by tarmoj** [comment]
Hi!

This is a known and problematic issue. It is caused by fltk widgets that interferes with the clipboard, there is no good way out.
The solution is to remove (or move out) the following dll files from Csound installation directory: widgets.dll, virtual.dll

See more: https://github.com/CsoundQt/CsoundQt/issues/322

tarmo
