### ISSUE TITLE
Windows 10 Help View displays some characters wrong

### ISSUE THREAD

**Issue by frmaurer99** [CsoundQt/CsoundQt#346]
Displaying an item in the Help View does not display some characters correctly.

![image](https://user-images.githubusercontent.com/74378290/98987711-7f4e0c00-251e-11eb-82c4-f8f1a9fef252.png)

**Comment by tarmoj** [comment]
Thanks for the report!

I will examine it on Windows when I will get a chance (and unfortunately that might be not so soon... )

Tarmo

**Comment by oliversandli** [comment]
First off, this is an absolutely awesome program! I love the code graph especially.

I'm having this issue too. Lots of `â€”` and `Â` characters where they definitely shouldn't be. Opening the docs "normally" in Firefox, etc. works just fine. I would really appreciate a fix!

Note that I am familiar with Python programming, so I'd be more than willing to help work on fixing this.

**Comment by oliversandli** [comment]
Most likely, the documents are *not* being read in UTF-8 mode (something to do with `QWebView`?). I have encountered this problem before when loading HTML documents in programs.

**Comment by oliversandli** [comment]
Aha! I found a fix without modifying the program. Adding the `charset` parameter in the headers of the source docs makes them render correctly.
From
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
```
to
```xml
<?xml version="1.0" encoding="UTF-8" charset="UTF-8" standalone="no"?>
```

**Comment by joachimheintz** [comment]
interesting, thanks for figuring out.  where exactly did you change 
this?  in the csound manual, or anywhere in the csoundqt sources?

**Comment by tarmoj** [comment]
Hi!

Actually CsoundQt should be able to handle it correctly, I need to try some
things on Windows.

Tarmo

T, 16. märts 2021 11:46 joachimheintz ***@***.***> kirjutas:

**Comment by oliversandli** [comment]
@joachimheintz I made the modification in one of the doc files in `C:\Program Files\Csound6_x64\doc\manual`.

**Comment by oliversandli** [comment]
@tarmoj If you need screenshots I'd be happy to oblige.

**Comment by oliversandli** [comment]
Hmm, it seems that Windows is definitely the culprit. After some digging around, I discovered that these "faulty" characters are caused by UTF-8 text being read as CP-1252 text. This is why Firefox works (it uses standard UTF-8), but more "local" applications don't (they use the OS's default character encoding).
I ran this in PowerShell and my fears were confirmed:
```powershell
PS C:\Users\Oliver> [System.Text.Encoding]::Default


IsSingleByte      : True
BodyName          : iso-8859-1
EncodingName      : Western European (Windows)
HeaderName        : Windows-1252
WebName           : Windows-1252
WindowsCodePage   : 1252
IsBrowserDisplay  : True
IsBrowserSave     : True
IsMailNewsDisplay : True
IsMailNewsSave    : True
EncoderFallback   : System.Text.InternalEncoderBestFitFallback
DecoderFallback   : System.Text.InternalDecoderBestFitFallback
IsReadOnly        : True
CodePage          : 1252
```
Sadly, there doesn't seem to be a way to change Windows' default encoding. (And doing so would probably be fraught with wacky errors.)

**Comment by oliversandli** [comment]
Has there been any progress on this? If not, could you point me to the code that shows the help/documentation window? From there I can try to fix it myself.

**Comment by frmaurer99** [comment]
I just added charset="UTF-8" to ALL the html files in C:\Program Files\Csound6_x64\doc\manual and I still have problems with some characters showing up funny in the Help window

![CSountQt_Help](https://user-images.githubusercontent.com/74378290/113439141-daa36c80-93e1-11eb-809e-5a23deae9ed1.jpg)

**Comment by oliversandli** [comment]
Yes @frmaurer99 , I was mistaken. The docs sometimes render properly, and sometimes don't. That "fix" corresponded with one of the random times that things were working. Sigh.

**Comment by tarmoj** [comment]
Hi!

Thanks for a little push and sorry for taking  it so long.
I think think I fixed it (seems to work on Windows 10 at least), please try.
I uploaded an zipped folder of the build here:
http://tarmo.uuu.ee/varia/failid/cs/CsoundQt/CsoundQt-1.0.0-beta2-Wind64.zip

tarmo

**Comment by frmaurer99** [comment]
Hi!

I extracted the zip and I ran CsoundQt-d-html-cs6.exe in the bin folder.
The program opens displaying the Help Screen and then exits almost
immediately

Thanks
Frank.

**Comment by tarmoj** [comment]
Hi!

I wonder if it is some kind of pacakaging error or due to that "fix" - does
CsoundQt works on otherwise? If you manage somehow to close the help
panel...

I try to test later on another machine.

Tarmo

P, 4. aprill 2021 14:39 frmaurer99 ***@***.***> kirjutas:

**Comment by frmaurer99** [comment]
No, the whole application just disappears after a second...

**Comment by tarmoj** [comment]
Hi!

I donwloaded the zip file on another Windows 7 machine, it worked and
displayed the manual correctly.
I guess otherwise CsoundQt works in you computer? I bet you do have Csound
installed separately?
Most likely there might be some conflict with the previous installation.
What happens if you move the CsoundQt-d-html-cs6.exe from the zip folder to
your original folder (rename or move away the original) and run it from
there?
Do you get any error messages about missing dll-s or anything else that
might be helpful?
Oliver, can you try how it works for you?

tarmo

Kontakt frmaurer99 ***@***.***>) kirjutas kuupäeval P, 4.
aprill 2021 kell 16:52:
