### ISSUE TITLE
add jack module for windows selection

### ISSUE THREAD

**Issue by joachimheintz** [CsoundQt/CsoundQt#373]
when jack is intalled for windows, nevertheless it cannot be selected as RT audio module.
can this be added?

**Comment by tarmoj** [comment]
Hi!

Makes sense. I hope to check it out on Winsows in coming days (hopefully).

tarmo

Kontakt joachimheintz ***@***.***>) kirjutas kuupäeval R,
11. märts 2022 kell 07:24:

**Comment by tarmoj** [comment]
Hi!

I had a look  - it is a problem of core Csound. CsoundQt uses csoundGetModule API call to get the available modules. It makes sense that jack is not reported on Windows since the default Windows build does not include the jack plugin  (jack.dll or how ever it should be called).
I guess your best bet is to install Jack with  JACK-Router  support (selectable by Jack installation), in CsoundQt choose portaudio as audio driver and amoung input and output devices you should see Jack-Asio Router and you can use that. I am not sure if it gives any advantage though...

tarmo
