### ISSUE TITLE
exitnow opcode crashes CsoundQt

### ISSUE THREAD

**Issue by csounder** [CsoundQt/CsoundQt#390]
It seems that the exitnow opcode does exitnow, but crashed CsoundQt

**Comment by tarmoj** [comment]
Hi!

Thanks! I can confirm. Seems that exitnow does not work when Csound is used
as library inside another program. See documentation
https://csound.com/manual/exitnow:
" Exit Csound as fast as possible, with no cleaning up."
The 'no cleaning up' causes problems for CsoundQt and exitnow should be
avoided.
If CsoundQt is built with PythonQt support, a python call to q.stop() would
do the job.

Otherwise you can use perhaps a button with reserved channel "_Stop", see
Examples->CsoundQt->Widgets->Reserved_Channels.csd

Tarmo



Kontakt Dr. Richard Boulanger ***@***.***>) kirjutas
kuupäeval P, 29. oktoober 2023 kell 19:16:

**Comment by joachimheintz** [comment]
we can use event "e" instead.  it is less brutal but does what we want:

instr Do
   outall(pinkish(.1))
endin
schedule("Do",0,-1)

instr Exit
   event_i("e",0)
endin
schedule("Exit",5,0)

	joachim

**Comment by csounder** [comment]
Thanks!

*- Dr.B*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division
