### ISSUE TITLE
file with <html> tag always creates new .html file

### ISSUE THREAD

**Issue by joachimheintz** [CsoundQt/CsoundQt#391]
whenever i have any .csd with a html tag in it
(try just with an empy `<html></html>` on top of any .csd file)
csoundqt creates a html file in the same directory:
test.csd will result in an additional test.csd.html file.

why?
for me this is annoying, and i cannot see any option to prevent it.

perhaps a leftover in the code, not meant to be like this?

**Comment by tarmoj** [comment]
Hi!

Creating another html file is necessary since CsoundQt injects some code
that are necessary for the QWebEngine (basically Chromium browser) to work.
It cannot be saved into a temporary directory since user may want to use
images, javascript libraries or other resources in their html code and most
typically links to it  are relative.

But indeed, user does not need these files and they should be deleted on
stop. I will have a look.

Tarmo

Kontakt joachimheintz ***@***.***>) kirjutas kuupäeval R,
22. detsember 2023 kell 20:01:

**Comment by joachimheintz** [comment]
thanks for explaining the background, tarmo!
deleting on closing csoundqt would be great if possible.

**Comment by tarmoj** [comment]
Hi!

I pushed a fix where the temporary html is deleted after it has been loaded. Thanks for bringing it out!

I will do some more work to optimize the webengine usage before a release of  v 1.1.2  soon.

tarmo

**Comment by joachimheintz** [comment]
excellent --- i checked it and it works perfectly.
i am doing a tutorial for html GUI; perhaps we can include it in the 
next release.

cheers -
	joachim
